In [1]:
import numpy as np
# np is the alias

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(4,)

In [7]:
b = [[1,2,3,4],[5,6,7,8]]
b = np.array(b)
b.shape

(2, 4)

In [8]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [10]:
np.dot(b, b.T)

array([[ 30,  70],
       [ 70, 174]])

In [12]:
np.random.randint(60, 100, 10)

array([67, 86, 98, 81, 62, 80, 74, 94, 92, 60])

In [16]:
matrix = np.random.randint(1,100, (5,5))
matrix

array([[93, 88, 44, 37, 20],
       [72, 28, 11, 40, 17],
       [16, 79, 47, 95, 25],
       [39, 62, 99, 63, 88],
       [67, 46, 67, 65, 94]])

In [17]:
np.max(matrix)

99

In [18]:
np.min(matrix)

11

In [32]:
a = np.array([1,2,3,-6,18,-21,10,10,10,10,10,3,3,3,2,1,18])

In [33]:
np.argmin(a)

5

In [34]:
np.argmax(a)

4

In [37]:
# contains only the unique elements and the elements are sorted in ascending order
b = np.unique(a, return_counts= True)
b

(array([-21,  -6,   1,   2,   3,  10,  18]), array([1, 1, 2, 2, 4, 5, 2]))

In [38]:
b[0]

array([-21,  -6,   1,   2,   3,  10,  18])

In [40]:
b[1]

array([1, 1, 2, 2, 4, 5, 2])

In [42]:
type(b)

tuple

In [43]:
b[0][(np.argmax(b[1]))]

10

In [44]:
matrix

array([[93, 88, 44, 37, 20],
       [72, 28, 11, 40, 17],
       [16, 79, 47, 95, 25],
       [39, 62, 99, 63, 88],
       [67, 46, 67, 65, 94]])

In [45]:
matrix[0,1]

88

In [46]:
matrix[4,4]

94

In [47]:
matrix[2][2]

47

In [50]:
matrix[0:3, 0:2]

array([[93, 88],
       [72, 28],
       [16, 79]])

In [51]:
matrix[:, 0]

array([93, 72, 16, 39, 67])

In [52]:
matrix[0, :]

array([93, 88, 44, 37, 20])