In [2]:
import numpy as np
a = np.zeros(3)
print(a)
print(type(a))
print(type(a[0]))

[0. 0. 0.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [4]:
z = np.zeros(10)
print(z)
print(z.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)


In [5]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
z = np.empty(4)
z

array([0., 0., 0., 0.])

In [8]:
z = np.linspace(2,10, 5)
print(z)
z = np.linspace(2,10, 7)
print(z)

[ 2.  4.  6.  8. 10.]
[ 2.          3.33333333  4.66666667  6.          7.33333333  8.66666667
 10.        ]


In [9]:
z = np.array([10,20])
z

array([10, 20])

In [11]:
name_of_a_list = [i for i in range(1,7)]
z = np.array(name_of_a_list)
z
type(z)

numpy.ndarray

In [12]:
z = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(z.shape)
print(z)


(2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [16]:
?z.shape
z.reshape((3,4))
z

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
np.random.seed(0)
z1 = np.random.randint(10, size = 6)
z1

array([5, 0, 3, 3, 7, 9])

In [18]:
z1[0]


5

In [19]:
z1[0:2]

array([5, 0])

In [20]:
z1[-1]

9

In [2]:
from skimage import io
photo = io.imread('york_minster.jpg')
print(type(photo))

FileNotFoundError: No such file: 'C:\Users\MERCURI\Documents\Machine Learning\Numpy basics\york_minster.jpg'